window.TG123_SKILLS = [
['acs','影音','剪映／CapCut 自動剪輯、對標分析、字幕與匯出。'],
['acs2','影音','依參考短片復刻剪輯節奏與版型。'],
['ai-auto-short-video-workflow','影音','長影音自動轉多支 9:16 短影音。'],
['ans','影音','微信小程式 AI 影片生成與下載流程。'],
['auto-reasoning-router','系統','依任務複雜度選擇推理強度與執行路由。'],
['bb-browser','瀏覽器','帶登入狀態的網頁資料取得與自動化操作。'],
['binance-coin-research','研究','幣安 Coin、迷因幣與鏈上資訊研究。'],
['character-memory-manager','角色','管理人物臉部、服裝、聲音與角色一致性。'],
['cls','文案','Claude 分析、腳本、拍攝計畫與短影音企劃。'],
['cmsd','影音','Claude 文案到 IMS 分鏡再到 SD 影片。'],
['codex-skill-handoff','系統','技能、記憶與工作流的匯出及跨端交接。'],
['codex-zuotu-lanxin','圖片','藍星做圖、確認清單、原圖下載與文件交付。'],
['douyin-peipao','營運','抖音陪跑、內容規劃與帳號營運。'],
['dreamina-cli','影音','Dreamina 影片生成、監控與成品下載。'],
['dreamina-sd-video-workflow','影音','Dreamina／Seedance 圖生影片完整流程。'],
['find-skill','系統','搜尋最符合任務的本機技能。'],
['github-pages-deploy','網站','GitHub Pages 建站、推送與公開驗證。'],
['hfsw','影音','文案、圖片、旁白、字幕、配樂、合成與完整 QA。'],
['hyperframes','影音','程式化影片畫面、動畫與視覺合成。'],
['imagegen','圖片','系統圖片生成能力入口；依規則自動路由。'],
['imagegen-disabled-use-lanxin','圖片','防誤觸入口，圖片任務改走藍星平台。'],
['imagegen-poster-telegram','圖片','海報生成與 Telegram 原檔交付入口。'],
['ims','圖片','圖片、海報、視覺設計與分鏡產出。'],
['lanxin-image-workflow','圖片','藍星圖片生成、下載、驗證與交付。'],
['lobster-working-style','系統','龍蝦工作風格、閉環執行與主人驗收原則。'],
['mininew-bridge-handoff','營運','微新系統、橋接流程與交接管理。'],
['monthly-course-site-updater','網站','每月課程網站內容更新與部署。'],
['nbps','NBS','NotebookLM Podcast／音訊摘要流程。'],
['nbs','NBS','NotebookLM 來源、摘要、音訊與簡報主流程。'],
['nbs-media-summary-pack','NBS','多媒體摘要成品整理與驗證。'],
['nbs-skill','NBS','NBS 任務路由與標準化操作入口。'],
['nbvs','NBS','NotebookLM 影片摘要與視覺輸出。'],
['new-customer-bot-base','營運','新客戶 Telegram Bot 基礎系統建立。'],
['nms-digital-human','影音','數位人腳本、畫面、語音與影片工作流。'],
['notebooklm-brief-to-deck-workflow','NBS','資料簡報化與 deck 產出流程。'],
['notebooklm-presentation-prompt','NBS','高品質簡報提示詞與內容結構。'],
['notebooklm-source-builder','NBS','整理、清洗與建立 NotebookLM 來源。'],
['notion-knowledge-capture','文件','把討論與成果整理成 Notion 知識。'],
['openai-docs','開發','OpenAI API、Codex 與模型官方文件。'],
['openclaw-browser-automation','瀏覽器','OpenClaw 瀏覽器登入與平台自動化。'],
['openclaw-desktop-control','系統','Windows 桌面操作與本機應用控制。'],
['operator-principles','系統','任務優先級、執行責任與驗收原則。'],
['owner-reply-style-telegram','營運','主人專用繁體中文 Telegram 回覆風格。'],
['pdf','文件','PDF 讀取、產出、轉換與驗證。'],
['playwright','瀏覽器','瀏覽器自動化、表單操作與頁面測試。'],
['playwright-interactive','瀏覽器','持續互動式瀏覽器操作與除錯。'],
['plugin-creator','開發','建立 Codex 插件與清單結構。'],
['screenshot','文件','畫面擷取、區域截圖與驗證。'],
['shamie-owner-reply-style','營運','蝦咩角色的主人回覆語氣與行為。'],
['skill-creator','開發','設計與建立可重複使用的 Codex 技能。'],
['skill-installer','開發','從本機或儲存庫安裝 Codex 技能。'],
['speech','語音','文字轉語音、聲線、語速與音訊輸出。'],
['teaching-step-images','圖片','多步驟教學圖、SOP 圖與批次驗證。'],
['telegram-bot-manager','營運','Telegram Bot 管理、媒體交付與同源規則。'],
['telegram-two-stage-reply','營運','Telegram 兩階段客服回覆與狀態銜接。'],
['tg123-daily-self-upgrade','系統','TG123 每日學習、技能修正與索引重建。'],
['transcribe','語音','音訊／影片語音轉錄、時間碼與字幕。'],
['video-frame-analysis','影音','逐格分析影片、畫面內容與剪輯節奏。'],
['video-spec-builder','影音','建立影片規格、分鏡、提示詞與驗收表。'],
['wbs','網站','網站建立、修改、驗證、部署與公開檢查。'],
['做圖','圖片','繁體中文圖片與海報的標準藍星工作流。']];
